export const IS_BufferFunctionType =
{
	AmplitudeModulatedSine: "AmplitudeModulatedSine",
	Buffer: "Buffer",
	Constant: "Constant",
	Impulse: "Impulse",
	InverseSawtooth: "InverseSawtooth",
	MovingAverage: "MovingAverage",
	Noise: "Noise",
	NoiseBand: "NoiseBand",
	Normalize: "Normalize",
	Pulse: "Pulse",
	QuantizedArrayBuffer: "QuantizedArrayBuffer",
	Ramp: "Ramp",
	RampBand: "RampBand",
	Sawtooth: "Sawtooth",
	Sine: "Sine",
	Splice: "Splice",
	Square: "Square",
	SuspendedOperations: "SuspendedOperations",
	Triangle: "Triangle",
	UnipolarNoise: "UnipolarNoise",
	UnipolarSine: "UnipolarSine",
	FrequencyModulatedSine: "FrequencyModulatedSine"
}